<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mos</string>
	</array>
	<key>name</key>
	<string>Xpress</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>IGNOREcomment</key>
			<string>built-in constants</string>
			<key>IGNOREmatch</key>
			<string>(?i:(r8|r4|\.TRUE\.|\.FALSE\.))</string>
			<key>IGNOREname</key>
			<string>constant.language.xpress</string>
		</dict>
		<dict>
			<key>IGNOREcomment</key>
			<string>numbers</string>
			<key>IGNOREmatch</key>
			<string>\b[\+\-]?[0-9]+\.?[0-9a-zA-Z_]*\b</string>
			<key>IGNOREname</key>
			<string>constant.numeric.xpress</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x:\s*([a-zA-Z\(\)]*)(?&lt;!end)\s*(?i:(function|subroutine|module|type|procedure))\b\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:(\()([^)]*)?  (\))?)?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.xpress</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.xpress</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.xpress</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.xpress</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.xpress</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.xpress</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>First line of function/subroutine definition</string>
			<key>end</key>
			<string>(?x:((?i:end))($|\s*(?i:function|subroutine|module|type|procedure)(\s+[A-Za-z_][A-Za-z0-9_]*)?))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.xpress</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.xpress</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.xpress</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?i:(integer|real|double\s+precision|complex|logical|character))\b(?=.*::)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.xpress</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Line of type specification</string>
			<key>end</key>
			<string>(?=!)|$</string>
			<key>name</key>
			<string>meta.specification.xpress</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>statements controling the flow of the program</string>
			<key>match</key>
			<string>\b(?i:(go\s*to|assign|to|if|then|else|elseif|elif|end\-if|select\s*case|case|end\s*select|end\s*if|continue|stop|pause|do|end\s*do|while|cycle|forall|do|end\-do))\b</string>
			<key>name</key>
			<string>keyword.control.xpress</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>programming units</string>
			<key>match</key>
			<string>\b(?i:(program|end\s+program|entry|block\s+data|call|return|contains|include))\b</string>
			<key>name</key>
			<string>keyword.control.programming-units.xpress</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operators</string>
			<key>match</key>
			<string>((?&lt;!\:=)\:=(?!\:=)|\-|\+|\/\/|\/|(?!^)\*|::|:=)</string>
			<key>name</key>
			<string>keyword.operator.xpress</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comparaciones</string>
			<key>match</key>
			<string>(?i:(&lt;\=|&gt;\=|\=|&lt;|&gt;|\!\=|&lt;&gt;))</string>
			<key>name</key>
			<string>keyword.operator.comparison.xpress</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)(?&lt;!\.)\b(
 __import__|abs|dynamic|array|declarations|end\-declarations|parameters|end\-parameters|write|writeln|of|mpvar|linctr|include|set|of|model|end\-model|
 exec|execfile|exit|fopen|fclose|initializations|end\-initializations|from|as|exists|getsize|
 input|true|false|intern|isinstance|issubclass|iter|len|license|locals|map|max|memoryview|
 min|next|open|ord|pow|print|property|quit|range|raw_input|reduce|reload|
 repr|reversed|round|setattr|sorted|sum|unichr|vars|zip
 )\b</string>
			<key>name</key>
			<string>support.function.builtin.xpress</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>logical operators</string>
			<key>match</key>
			<string>(?i:(\ and\ |\ or\ |\ eq\ |\ lt\ |\ le\ |\ gt\ |\ ge\ |\ ne\ |\ not\ |\ eqv\ |\ neqv\ ))</string>
			<key>name</key>
			<string>keyword.operator.logical.xpress</string>
		</dict>
		<dict>
			<key>IGNOREcomment</key>
			<string>brackets</string>
			<key>IGNOREmatch</key>
			<string>([\()])</string>
			<key>IGNOREname</key>
			<string>keyword.operator.parenthesis.xpress</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>data specification</string>
			<key>match</key>
			<string>\b(?i:(integer|real|double\s+precision|complex|logical|character|block\sdata|operator|assignment|type|boolean|string))\b</string>
			<key>name</key>
			<string>storage.type.xpress</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>data type attributes</string>
			<key>match</key>
			<string>\b(?i:(dimension|common|equivalence|parameter|external|intrinsic|save|data|implicit\s*none|implicit|intent|in|out|inout))\b</string>
			<key>name</key>
			<string>storage.modifier.xpress</string>
		</dict>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.xpress</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.xpress</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.xpress</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.escape.apostrophe.xpress</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.xpress</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.xpress</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.xpress</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>""</string>
					<key>name</key>
					<string>constant.character.escape.quote.xpress</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[Cc](?=\b|[Cc])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.xpress</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.c.xpress</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\s*\n</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.xpress</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.asterisk.xpress</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\s*\n</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#\s*(error|warning)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.error.xpress</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>meta.preprocessor.diagnostic.xpress</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.xpress</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#\s*(include|import)\b\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.xpress</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?://|/\*))|$\n?</string>
			<key>name</key>
			<string>meta.preprocessor.xpress.include</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.xpress</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.xpress</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.xpress</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.include.xpress</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.xpress</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.xpress</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.lt-gt.include.xpress</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[Cc](?=\b|[Cc])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.xpress</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.c.xpress</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\s*\n</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.xpress</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.asterisk.xpress</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\s*\n</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>[!]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.xpress</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.asterisk.xpress</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\s*\n</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(!</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.xpress</string>
				</dict>
			</dict>
			<key>end</key>
			<string>!\)\n?</string>
			<key>name</key>
			<string>comment.block.source.xpress</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.xpress</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$
?</string>
			<key>name</key>
			<string>comment.line.double-slash.source.xpress</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.xpress</string>
	<key>uuid</key>
	<string>8e494bec-c003-4942-9a3a-b73fc1acfca6</string>
</dict>
</plist>
